baseURL = 'https://leenstx.github.io/blog/'
languageCode = 'en-us'
title = 'Leenstx'
theme = 'yinyang'


[author]
  name = "LeenstxÂ·"
  homepage = "https://leenstx.github.io/blog/"

[params]
mainSections = ["posts"]


[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "Github"
link = "https://github.com/leenstx/blog"
